### ISSUE TITLE
Does it support Migrations ?

### ISSUE THREAD

**Issue by PatrissolJuns** [kitar/laravel-dynamodb#13]
Thank you very much for this great work. However, I wanted to know if does it support migrations. Because a downside of it is that I keep on getting error of cannot do x operation on non-existent table

**Comment by kitar** [comment]
Thank you for discovering!

Unfortunately, we don't support migrations at this time.

I don't have a good idea to implement migrations at this time, but I'm happy to consider it. Maybe it should be implemented in this package, or maybe it is better to prepare another package. If you find some good migration package or idea, please let me know :)
