### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::usingModel()

### ISSUE THREAD

**Issue by andrewboohoo** [kitar/laravel-dynamodb#19]
I am getting error
```
Call to undefined method Illuminate\Database\Query\Builder::usingModel()
```

when trying to use package, for example 
```
$refunds = RefundsLog::scan();
```

Laravel v8.83.12

**Comment by kitar** [comment]
@andrewboohoo Thanks for the report! Can you share the code of `RefundsLog` model? (especially, the parts that use Eloquent features such as `casts`)

There may be some Eloquent features that this package not supported yet.

**Comment by Jonnx** [comment]
I am getting the same error using the following model just to try it out (dynamodb-local in docker)

```
<?php

namespace App\Models;

use Kitar\Dynamodb\Model\Model;

class DynamoUser extends Model
{
    protected $table = 'users';
    protected $primaryKey = 'email';
    protected $fillable = ['email', 'name', 'password'];
}

```

**Comment by umayanrmr** [comment]
I solve it by adding a ```protected $connection = 'dynamodb';``` to my model

**Comment by kitar** [comment]
I finally understand! Thank you for reporting @umayanrmr @Jonnx 

You have to set `DB_CONNECTION=dynamodb` in the `.env` file. If you do so, you don't need to override `protected $connection`. This is not in the document, so I'll add it soon.

**Comment by kitar** [comment]
I'll close this issue at this time. Please feel free to re-open if needed.

**Comment by gvanto** [comment]
> I finally understand! Thank you for reporting @umayanrmr @Jonnx
> 
> You have to set `DB_CONNECTION=dynamodb` in the `.env` file. If you do so, you don't need to override `protected $connection`. This is not in the document, so I'll add it soon.

What if I want to use both MySQL and DynamoDB in my application?

**Comment by kitar** [comment]
@gvanto
I believe you can manage it in the same way you would handle multiple MySQL databases.
https://fideloper.com/laravel-multiple-database-connections

**Comment by gvanto** [comment]
Thanks @kitar, think I will just use the below in my model as it seems to work just fine:

`protected $connection = 'dynamodb';`
