### ISSUE TITLE
InvalidArgumentException Unsupported driver [dynamodb].

### ISSUE THREAD

**Issue by jaronQ** [kitar/laravel-dynamodb#39]
I'm faced with this error:

Illuminate\Database\Connectors\ConnectionFactory::createConnection
/var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:287

Am I missing something here?

![image](https://github.com/kitar/laravel-dynamodb/assets/28611124/34ef3e7f-7fb2-4242-9a19-5d7fec82a916)

**Comment by kitar** [comment]
@jaronQ Sorry for the delayed reply. Could you provide more details about your setup? I'm interested in the version of Laravel you're using and how you're attempting to connect to DynamoDB—is it through a Model, the DB Facade, or `Kitar\Dynamodb\Connection`, etc.?

**Comment by kitar** [comment]
I'm closing this issue as it's no longer active. Please feel free to reopen it if the problem hasn't been resolved.

**Comment by jaronQ** [comment]
I was able to get it working with `Kitar\Dynamodb\Connection` - I saw the error when trying to use `::find` or `::all()` with the model methods.

**Comment by kitar** [comment]
@jaronQ Thanks for sharing! If you're still experiencing the issue, could you provide a bit more detail on how to reproduce the problem? It might help me assist you better.
