### ISSUE TITLE
Endpoint config issue when using with Docker

### ISSUE THREAD

**Issue by gvanto** [kitar/laravel-dynamodb#41]
I am using docker and my endpoint is: 
DYNAMODB_ENDPOINT=dynamodb:8000

This causes failure:
![image](https://github.com/kitar/laravel-dynamodb/assets/8372918/8df014fb-6a67-4673-99c6-353acf9fe371)

Suggested edit (ie let developer specify the exact endpoint they want to use, dont force https or even http onto it):
<img width="1265" alt="image" src="https://github.com/kitar/laravel-dynamodb/assets/8372918/9443b559-665c-477a-9eaf-177eb1acef14">

**Comment by kitar** [comment]
btw, this is unrelated to the issue... I actually visited Cape Town as a child while living in Botswana. It's great to have you trying out this library :)

**Comment by gvanto** [comment]
> @gvanto Could you please try the following?
> 
> ```
> DYNAMODB_ENDPOINT=http://dynamodb:8000
> ```
> 
> Related: #18

That worked, thanks so much @kitar !

Awesome that you visited our beautiful city :)

In 2018 I visited Tokyo (and climbed Fuji, what an experience! Not easy ...) and absolutely loved it.

Shot for a great library!

**Comment by kitar** [comment]
Wow, you've been to Japan before! That must have been an amazing challenge. I guess I need to climb Fuji too :)

**Comment by gvanto** [comment]
Hi @kitar yes it was an unbelievable trip! Yakitori 🤤 

When I finally came down Fuji again, very very exhausted, I spoke to a Japanese guy who said that in Japan they have a saying "you must go up Fuji once in your life, but if you go up again, you are an idiot!" 😂
