### ISSUE TITLE
Support PHP 8.3 with Laravel 11

### ISSUE THREAD

**Issue by Mahan-Shoghy** [kitar/laravel-dynamodb#45]
When I try install in Laravel 10 and PHP 8.1 it's ok!
but when I upgrade to Laravel 11 and PHP 8.3 I got this errors:

Problem 1
    - kitar/laravel-dynamodb[v0.1.0, ..., v0.2.0] require php ^7.2 -> your php version (8.3.3) does not satisfy that requirement.
    - kitar/laravel-dynamodb[v0.3.0, ..., v0.6.0] require illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - kitar/laravel-dynamodb[v1.0.0, ..., v1.1.0] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - kitar/laravel-dynamodb[v1.1.1, ..., v1.2.0] require illuminate/support ^6.0|^7.0|^8.0|^9.0|^10.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires kitar/laravel-dynamodb * -> satisfiable by kitar/laravel-dynamodb[v0.1.0, ..., v0.6.0, v1.0.0, ..., v1.2.0].

**Comment by kitar** [comment]
I'm currently working on adding support for Laravel 11 and PHP 8.3! We appreciate your patience as we make these updates.

**Comment by kitar** [comment]
@Mahan-Shoghy All set! Please feel free to reopen the issue if there are any remaining problems.
