### ISSUE TITLE
Can't Run Migrations

### ISSUE THREAD

**Issue by dxrrxns** [kitar/laravel-dynamodb#50]
We are using laravel 11 for a new project and cannot run any migrations or use the refresh trait on tests because there is no Schema Grammar class for your DynamoDB package. At least that's what the issue initially appears to be. Any chance this is in the works somewhere or I am just overlooking something?

We will probably just write out own refresh trait and migration commands, but was curious if anyone else had run into the problem. It might be new to v11.

Part of me also thinks writing a schema grammar for Dynamo is just trying to marry this too close to SQL and we should just treat it as the different animal that it is.

**Comment by kitar** [comment]
Thanks for your comment :) As you point out, there is currently no built-in way to run migrations. You will need to write your own code to refresh the database during tests as well.

It would be great if there were features to support testing, but I also agree that writing a schema grammar for DynamoDB might be overkill, and I haven't found the right solution yet. (By the way, I wrote the following in the doc)

> I don't want to make it fully compatible with Eloquent because DynamoDB is different from relational databases.

Just to add, the reason I made this package even though DynamoDB is different from SQL is that it is sufficient for simple use cases. Specifically, my initial motivation for creating this package was to use DynamoDB as a custom user provider for Laravel's authentication.
